MAF: "Data/Somatic_mutation_wxs/CPTAC_maf_annotated_simplified.txt"
CNV: "Data/Somatic_cnv/CPTAC_cna_driver_calls.txt"
FULLMAF: "Data/Somatic_mutation_wxs/Broad_WashU_union/PanCan_Union_Maf_Broad_WashU_v1.1.maf"
FULLCNV: "Data/Somatic_cnv/Broad_pipeline_wxs_formatted/GISTIC_all_thresholded.by_genes.tsv"
RNA: "Data/Gene_expression/ALL_RNA-Seq_Expr_WashU_FPKM_UQ_annotation.tsv"
PROT: "Data/Proteome/Broad_updated_tumor_NAT/Proteome_Broad_updated_tumor_NAT_raw_gene_level_v1.3.tsv"
CLIN: "Data/Clinical_data/clinical_Pan-cancer.Jan2022.tsv"
MUTCO: "Data/Drivers/mutual_coocurrance.txt"
META: "Data/Meta_table/CPTAC-Pancan-Data_metatable.txt"
CLUST: "Data/Clustering/CPTAC-Pancan-Data_metatable.txt"
DRIVERS: "Data/GeneLists/299.genes.txt"
NEST: "Data/NESTs/TheNEST.csv"
SUBTYPE: "Data/Clinical_data/prosp-brca-v5.3-sample-annotation.csv"
